#!/bin/bash
CUDA_VISIBLE_DEVICES=0,1 python train.py \
--shuffle --batch_size 1024 --parallel \
--num_G_accumulations 2 --num_D_accumulations 2 --num_epochs 500 \
--num_D_steps 4 --G_lr 2e-4 --D_lr 2e-4 \
--dataset C10 \
--G_ch 96 --D_ch 96 \
--G_shared \
--G_ortho 0.0 \
--G_attn 0 --D_attn 0 \
--G_init N02 --D_init N02 \
--ema --use_ema --ema_start 1000 \
--hier --dim_z 120 --shared_dim 128 \
--G_init ortho --D_init ortho \
--save_every 50 --num_best_copies 5 --num_save_copies 2 --seed 0 \
--data_root /fs/vulcan-scratch/ilyak/locDoc/data/cifar10 \
--weights_root /fs/vulcan-scratch/ilyak/locDoc/experiments/biggancifar \
--logs_root /fs/vulcan-scratch/ilyak/locDoc/experiments/biggancifar \
--samples_root /fs/vulcan-scratch/ilyak/locDoc/experiments/biggancifar \
--test_every 20000000 \
--experiment_name table1row7 \
--historical_save_every 100